### PR TITLE
Move SQL MI provision to Before HOL ARM Template

### PR DESCRIPTION
**Pull request by crpietschmann**
This addresses issue of Azure SQL Managed Instance taking up to 4 hours to provision by moving the provisioning of it to the Before HOL ARM Template deployment.

Related to Issue #4

### CODE REVIEW

**Review by daneenec — COMMENTED** [review]
@DawnmarieDesJardins These changes are ready for your review

**Comment by DawnmarieDesJardins** [comment]
Hello @crpietschmann @daneenec 
Thanks for this!  I only have 2 questions:

- I believe we need to adjust the duration times for both documents.  The Before the HOL is currently 30 minutes, and Exercise 1 of the HOL is 90 minutes.  My guess is the HOL is now shorter, the Before the HOL is longer.
- The HOL has a note that states the SQL MI can take up to 4 hours to provision.  Should we have a matching warning in the Before the HOL?

**Comment by crpietschmann** [comment]
> Hello @crpietschmann @daneenec Thanks for this! I only have 2 questions:
> 
> * I believe we need to adjust the duration times for both documents.  The Before the HOL is currently 30 minutes, and Exercise 1 of the HOL is 90 minutes.  My guess is the HOL is now shorter, the Before the HOL is longer.
> * The HOL has a note that states the SQL MI can take up to 4 hours to provision.  Should we have a matching warning in the Before the HOL?

I updated the duration for "Exercise 1: SQL database migration" to be a little shorter since it no longer includes provisioning SQL MI. The Before HOL duration is the same since we didn't add steps for this change as it was another resource addd to the ARM Template deployment.

The Before HOL has mention that the ARM Template can take up to 4 hours to complete. Is that enough, or should I add mention of SQL MI? 

@DawnmarieDesJardins  @daneenec

**Comment by DawnmarieDesJardins** [comment]
@crpietschmann  
> I updated the duration for "Exercise 1: SQL database migration" to be a little shorter since it no longer includes provisioning SQL MI. The Before HOL duration is the same since we didn't add steps for this change as it was another resource addd to the ARM Template deployment.
> 
> The Before HOL has mention that the ARM Template can take up to 4 hours to complete. Is that enough, or should I add mention of SQL MI?

Thank you!  If the durations are correct, no need to add that second note.  You said ARM template, I was looking for SQL MI, but it appears they're the same thing.  That's why I have to ask, sorry.  I'll merge the PR and close the issues.

**Pull request merged**
